### ISSUE TITLE
Add screenshot to the README

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/CSS-Nintendo-Joystick#1]
Add screenshot to the README of the project

**Comment by NeuralNinja57** [comment]
hi,
i would like to take up this issue.
What do I have to do ?
Please provide me with the details.

**Comment by TheAdnan** [comment]
Basically just clone the repo, run in it your browser and make a screenshot of the Joystick.
After that, update the readme with that picture.

**Comment by NeuralNinja57** [comment]
by joystick, you mean the NES controller, right ?

**Comment by TheAdnan** [comment]
Yeah, that.

**Comment by NeuralNinja57** [comment]
My PR #3

**Comment by TheAdnan** [comment]
Nope, I said: 

> Basically just clone the repo, run in it your browser and make a screenshot of the Joystick.
After that, update the readme with that picture.

So not the existing jpg image that I've added, but the html/css generated item.
